### ISSUE TITLE
Roadmap to alpha 🗺 

### ISSUE THREAD

**Issue by EricThomson** [EricThomson/deepglue#1]
Tentative plans to get to a working alpha

The following aren't necessarily in order in which they will be checked off. 

**Note**: this is not currently in active development.

## Must haves
- [X] Test infrastructure set up
  - [X] move fixtures to `conftest.py`
- [X] Basic training (training/validation/inference) (`training_utils.py`)
- [X] Basic plotting functions (`plotting_utils.py`)
- [X] Basic file i/o utils (`file_utils.py`)
- [X] CI/CD including basic linting, running of tests, pushing to pypi `workflows/ci_cd.yml`
- [X] Basic docs written (using mkdocs) (in `docs/`)
  - [X] Serve at readthedocs.
- [x] Ensure visualization/training works with greyscale and rgb.
- [x] Interactive visualization of feature clusters (umap and pca).
- [x] Build a demo notebook for fashion-mnist
  - [x] Ensure demo works at Colab
- [x] CONTRIBUTORS.md and Code of Conduct
- [ ] Add checkpoints to train_and_validate()
- [ ] Instead of just getting dicts of data category counts: functions for plotting them in nice way
- [ ] Random seed handling
- [ ] Add explanation of learning rate schedulers
- [ ] Add tooling for imbalanced data
  - [ ] Demo notebook for handling imbalanced data

## Nice to have
- [ ] Feature-map visualization.
